[package]
name = "pdex"
version = "0.1.0"
authors = ["Miguel Young de la Sota <mcyoung@mit.edu>"]
edition = "2018"

[dependencies]
crossbeam = "0.8.0"
pkmn = { path = ".." }
single_value_channel = "1.2.2"
termion = "1.5"
tui = "0.14.0"